### ISSUE TITLE
Supporting responses containing CNAME records 

### ISSUE THREAD

**Issue by anikravesh** [MiniDNS/minidns#67] opened 2017-08-21 16:58 UTC
When the response to a A query contains CNAME records, the set of returned Answers will be empty.
```
ResolverResult<A> resolver = api.resolve("s3.amazonaws.com", A.class);
if(resolver.wasSuccessful()){
      Set<A> answers = resolver.getAnswers();
      Log.d(TAG, answers.size());
}
```

**Comment by Flowdalic** [comment] 2017-08-21 21:48
Related to #32

**Comment by Flowdalic** [comment] 2018-07-07 08:15
In fact, this is a duplicate of #32.

**Closed by Flowdalic** 2018-07-07 08:15 UTC
